# Generated by Django 4.0 on 2022-03-17 15:35

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_details_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.models.filepath),
        ),
    ]
